spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/mydatabase
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  h2:
    console:
      enabled: true
  flyway:
    enabled: true
    locations: classpath:db/migration